name: novotix_app
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  cupertino_icons: ^1.0.1
  qr_code_scanner: ^0.1.0
  flutter_switch: ^0.2.0
  audioplayers: ^0.17.0
  http: ^0.12.2
  flutter_svg: ^0.19.2+1
  connectivity: ^2.0.2
  fluttertoast: ^7.1.6
  modal_progress_hud: ^0.1.3
  path_provider: ^1.6.24
  sqflite: ^1.3.2+1
  intl: ^0.17.0-nullsafety.2
  shared_preferences: ^0.5.12+4
  firebase_messaging: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/invalid.mp3
    - assets/success.mp3
    - assets/warning.mp3
    - images/background.png
    - images/icons/iconcheck.png
    - images/icons/menu.svg
    - images/icons/nt.svg
    - images/icons/out.svg
    - images/icons/read.svg
    - images/icons/tap.svg
    - images/icons/unread.svg
    - images/login_image.png
    - images/logo.png
  fonts:
     - family: Poppins
       fonts:
         - asset: fonts/Poppins-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
