/// Generated by AssetsRefGenerator on 2020/12/29
class Res {
  static const String invalid = "assets/invalid.mp3";
  static const String success = "assets/success.mp3";
  static const String warning = "assets/warning.mp3";
  static const String background = "images/background.png";
  static const String iconCheck = "images/icons/iconcheck.png";
  static const String menu = "images/icons/menu.svg";
  static const String nt = "images/icons/nt.svg";
  static const String out = "images/icons/out.svg";
  static const String read = "images/icons/read.svg";
  static const String tap = "images/icons/tap.svg";
  static const String unread = "images/icons/unread.svg";
  static const String login_image = "images/login_image.png";
  static const String logo = "images/logo.png";
}
